global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'proyecto-cicd-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mi-aplicacion'
    scrape_interval: 10s
    static_configs:
      - targets: ['mi-app:3000']
        labels:
          app: 'mi-app'
          environment: 'local'
    metrics_path: '/metrics'
